### ISSUE TITLE
Devise a means for end users to run checks/tests against a downloaded release

### ISSUE THREAD

**Issue by oubiwann** [lfe/olp#23]
This would not be a task for developers, but rather for end users. As such, the mechanism selected for testing should not depend upon the development toolchain. We should only rely upon what is actually in the release itself.

As such, the following tasks might be appropriate:
 * [ ] Bundle the rebar binary with the release - #24
 * [ ] Ensure that the LFE tests can be run from LFE or Erlang (or use LFE/Erlang executables, e.g., `ct`) - #25
 * [ ] Determine how to run `rebar3` from "inside" the release when testing as an end user - #26
 * [ ] Provide a single means of running all tests "within" the release - #27

Part of epic #20
