### ISSUE TITLE
Support multiple releases

### ISSUE THREAD

**Issue by oubiwann** [lfe/olp#35]
Features:

 * [ ] Support an LFE-only (no libs) release
 * [ ] Support an LFE-essentials (just a few libs) release
 * [ ] Support an LFE-web (web dev libs) release
 * [ ] Support an LFE-dev (all libs) release

Part of release #1
