### ISSUE TITLE
Examine Release Use Cases

### ISSUE THREAD

**Issue by oubiwann** [lfe/olp#36]
In order to make sure that OLP is built in a manner useful for all sorts of sitiations, we need to examine the anticipated use cases (and then test OLP with those, possibly making changes during this process of discovery).

Use Cases:
 * [ ] Using OLP and it's executables (`lfe`, `lfescript`, `erl`, `erlscript`) on a system with no Erlang installed
 * [ ] Using OLP on a system that has Erlang installed
 * [ ] Using OLP (on Erlang-less system) to develop and build LFE applications
 * [ ] Using OLP (on Erlang-less system) to deploy/run one or more custom LFE applications
 * [ ] Using OLP to generate a custom release that contains all of OLP but also libraries of a user's choosing

Part of release #1
